# Generated by Django 5.2 on 2026-02-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postdayBackend', '0002_postnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postnews',
            old_name='created_At',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
