# Generated by Django 6.0.2 on 2026-02-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postdayBackend', '0006_alter_postnews_likes_alter_postnews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postnews',
            name='body',
            field=models.CharField(),
        ),
    ]
